name: example-application-manifest
custom_specs: my-specs/tools
tools:
  - name: java
    checks:
      version: ">= 11.0.0"
  - name: go
    checks:
      version: ">= 1.14"
  - name: golangci-lint
    checks:
      version: "= 1.23.8"
  - name: node
    checks:
      version: ">= 12.13.1"
