name: example-application-manifest
custom_specs: .enval
tools:
  - name: go
    checks:
      version: ">= 1.14"
  - name: gotestsum
    checks:
      version: "= 0.4.0"
  - name: golangci-lint
    checks:
      version: "= 1.23.8"
  - name: packr
    checks:
<<<<<<< HEAD
      version: ">= 4.0"
  - name: enval
    checks:
      version: ">= 0.1.0"
=======
      version: ">= 2.5.3"
>>>>>>> master
